--
-- JBoss, Home of Professional Open Source
-- Copyright 2013, Red Hat, Inc. and/or its affiliates, and individual
-- contributors by the @authors tag. See the copyright.txt in the
-- distribution for a full listing of individual contributors.
--
-- Licensed under the Apache License, Version 2.0 (the 'License');
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
-- http://www.apache.org/licenses/LICENSE-2.0
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an 'AS IS' BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--

-- You can use this file to load seed data into the database using SQL statements
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (1, 'AFGHANISTAN', 'Afghani', '971', 'AFN', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (2, '�LAND ISLANDS', 'Euro', '978', 'EUR', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (3, 'ALBANIA', 'Lek', '008', 'ALL', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (4, 'ALGERIA', 'Algerian Dinar', '012', 'DZD', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (5, 'AMERICAN SAMOA', 'US Dollar', '840', 'USD', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (6, 'ANDORRA', 'Euro', '978', 'EUR', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (7, 'ANGOLA', 'Kwanza', '973', 'AOA', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (8, 'ANGUILLA', 'East Caribbean Dollar', '951', 'XCD', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (9, 'ANTIGUA AND BARBUDA', 'East Caribbean Dollar', '951', 'XCD', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (10, 'ARGENTINA', 'Argentine Peso', '032', 'ARS', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (11, 'ARMENIA', 'Armenian Dram', '051', 'AMD', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (12, 'ARUBA', 'Aruban Florin', '533', 'AWG', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (13, 'AUSTRALIA', 'Australian Dollar', '036', 'AUD', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (14, 'AUSTRIA', 'Euro', '978', 'EUR', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (15, 'AZERBAIJAN', 'Azerbaijanian Manat', '944', 'AZN', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (16, 'BAHAMAS', 'Bahamian Dollar', '044', 'BSD', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (17, 'BAHRAIN', 'Bahraini Dinar', '048', 'BHD', 3)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (18, 'BANGLADESH', 'Taka', '050', 'BDT', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (19, 'BARBADOS', 'Barbados Dollar', '052', 'BBD', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (20, 'BELARUS', 'Belarussian Ruble', '974', 'BYR', 0)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (21, 'BELGIUM', 'Euro', '978', 'EUR', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (22, 'BELIZE', 'Belize Dollar', '084', 'BZD', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (23, 'BENIN', 'CFA Franc BCEAO', '952', 'XOF', 0)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (24, 'BERMUDA', 'Bermudian Dollar', '060', 'BMD', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (25, 'BHUTAN', 'Ngultrum', '064', 'BTN', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (26, 'BHUTAN', 'Indian Rupee', '356', 'INR', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (27, 'BOLIVIA, PLURINATIONAL STATE OF', 'Boliviano', '068', 'BOB', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (28, 'BOLIVIA, PLURINATIONAL STATE OF', 'Mvdol', '984', 'BOV', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (29, 'BONAIRE, SINT EUSTATIUS AND SABA', 'US Dollar', '840', 'USD', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (30, 'BOSNIA AND HERZEGOVINA', 'Convertible Mark', '977', 'BAM', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (31, 'BOTSWANA', 'Pula', '072', 'BWP', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (32, 'BOUVET ISLAND', 'Norwegian Krone', '578', 'NOK', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (33, 'BRAZIL', 'Brazilian Real', '986', 'BRL', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (34, 'BRITISH INDIAN OCEAN TERRITORY', 'US Dollar', '840', 'USD', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (35, 'BRUNEI DARUSSALAM', 'Brunei Dollar', '096', 'BND', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (36, 'BULGARIA', 'Bulgarian Lev', '975', 'BGN', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (37, 'BURKINA FASO', 'CFA Franc BCEAO', '952', 'XOF', 0)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (38, 'BURUNDI', 'Burundi Franc', '108', 'BIF', 0)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (39, 'CAMBODIA', 'Riel', '116', 'KHR', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (40, 'CAMEROON', 'CFA Franc BEAC', '950', 'XAF', 0)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (41, 'CANADA', 'Canadian Dollar', '124', 'CAD', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (42, 'CABO VERDE', 'Cabo Verde Escudo', '132', 'CVE', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (43, 'CAYMAN ISLANDS', 'Cayman Islands Dollar', '136', 'KYD', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (44, 'CENTRAL AFRICAN REPUBLIC', 'CFA Franc BEAC', '950', 'XAF', 0)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (45, 'CHAD', 'CFA Franc BEAC', '950', 'XAF', 0)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (46, 'CHILE', 'Unidad de Fomento', '990', 'CLF', 4)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (47, 'CHILE', 'Chilean Peso', '152', 'CLP', 0)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (48, 'CHINA', 'Yuan Renminbi', '156', 'CNY', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (49, 'CHRISTMAS ISLAND', 'Australian Dollar', '036', 'AUD', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (50, 'COCOS (KEELING) ISLANDS', 'Australian Dollar', '036', 'AUD', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (51, 'COLOMBIA', 'Colombian Peso', '170', 'COP', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (52, 'COLOMBIA', 'Unidad de Valor Real', '970', 'COU', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (53, 'COMOROS', 'Comoro Franc', '174', 'KMF', 0)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (54, 'CONGO', 'CFA Franc BEAC', '950', 'XAF', 0)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (55, 'CONGO, DEMOCRATIC REPUBLIC OF THE ', 'Congolese Franc', '976', 'CDF', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (56, 'COOK ISLANDS', 'New Zealand Dollar', '554', 'NZD', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (57, 'COSTA RICA', 'Costa Rican Colon', '188', 'CRC', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (58, 'C�TE D"IVOIRE', 'CFA Franc BCEAO', '952', 'XOF', 0)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (59, 'CROATIA', 'Croatian Kuna', '191', 'HRK', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (60, 'CUBA', 'Peso Convertible', '931', 'CUC', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (61, 'CUBA', 'Cuban Peso', '192', 'CUP', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (62, 'CURA�AO', 'Netherlands Antillean Guilder', '532', 'ANG', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (63, 'CYPRUS', 'Euro', '978', 'EUR', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (64, 'CZECH REPUBLIC', 'Czech Koruna', '203', 'CZK', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (65, 'DENMARK', 'Danish Krone', '208', 'DKK', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (66, 'DJIBOUTI', 'Djibouti Franc', '262', 'DJF', 0)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (67, 'DOMINICA', 'East Caribbean Dollar', '951', 'XCD', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (68, 'DOMINICAN REPUBLIC', 'Dominican Peso', '214', 'DOP', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (69, 'ECUADOR', 'US Dollar', '840', 'USD', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (70, 'EGYPT', 'Egyptian Pound', '818', 'EGP', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (71, 'EL SALVADOR', 'El Salvador Colon', '222', 'SVC', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (72, 'EL SALVADOR', 'US Dollar', '840', 'USD', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (73, 'EQUATORIAL GUINEA', 'CFA Franc BEAC', '950', 'XAF', 0)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (74, 'ERITREA', 'Nakfa', '232', 'ERN', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (75, 'ESTONIA', 'Euro', '978', 'EUR', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (76, 'ETHIOPIA', 'Ethiopian Birr', '230', 'ETB', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (77, 'EUROPEAN UNION', 'Euro', '978', 'EUR', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (78, 'FALKLAND ISLANDS (MALVINAS)', 'Falkland Islands Pound', '238', 'FKP', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (79, 'FAROE ISLANDS', 'Danish Krone', '208', 'DKK', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (80, 'FIJI', 'Fiji Dollar', '242', 'FJD', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (81, 'FINLAND', 'Euro', '978', 'EUR', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (82, 'FRANCE', 'Euro', '978', 'EUR', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (83, 'FRENCH GUIANA', 'Euro', '978', 'EUR', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (84, 'FRENCH POLYNESIA', 'CFP Franc', '953', 'XPF', 0)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (85, 'FRENCH SOUTHERN TERRITORIES', 'Euro', '978', 'EUR', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (86, 'GABON', 'CFA Franc BEAC', '950', 'XAF', 0)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (87, 'GAMBIA', 'Dalasi', '270', 'GMD', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (88, 'GEORGIA', 'Lari', '981', 'GEL', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (89, 'GERMANY', 'Euro', '978', 'EUR', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (90, 'GHANA', 'Ghana Cedi', '936', 'GHS', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (91, 'GIBRALTAR', 'Gibraltar Pound', '292', 'GIP', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (92, 'GREECE', 'Euro', '978', 'EUR', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (93, 'GREENLAND', 'Danish Krone', '208', 'DKK', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (94, 'GRENADA', 'East Caribbean Dollar', '951', 'XCD', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (95, 'GUADELOUPE', 'Euro', '978', 'EUR', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (96, 'GUAM', 'US Dollar', '840', 'USD', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (97, 'GUATEMALA', 'Quetzal', '320', 'GTQ', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (98, 'GUERNSEY', 'Pound Sterling', '826', 'GBP', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (99, 'GUINEA', 'Guinea Franc', '324', 'GNF', 0)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (100, 'GUINEA-BISSAU', 'CFA Franc BCEAO', '952', 'XOF', 0)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (101, 'GUYANA', 'Guyana Dollar', '328', 'GYD', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (102, 'HAITI', 'Gourde', '332', 'HTG', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (103, 'HAITI', 'US Dollar', '840', 'USD', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (104, 'HEARD ISLAND AND McDONALD ISLANDS', 'Australian Dollar', '036', 'AUD', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (105, 'HOLY SEE (VATICAN CITY STATE)', 'Euro', '978', 'EUR', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (106, 'HONDURAS', 'Lempira', '340', 'HNL', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (107, 'HONG KONG', 'Hong Kong Dollar', '344', 'HKD', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (108, 'HUNGARY', 'Forint', '348', 'HUF', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (109, 'ICELAND', 'Iceland Krona', '352', 'ISK', 0)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (110, 'INDIA', 'Indian Rupee', '356', 'INR', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (111, 'INDONESIA', 'Rupiah', '360', 'IDR', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (112, 'INTERNATIONAL MONETARY FUND (IMF)', 'SDR (Special Drawing Right)', '960', 'XDR', 0)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (113, 'IRAN, ISLAMIC REPUBLIC OF', 'Iranian Rial', '364', 'IRR', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (114, 'IRAQ', 'Iraqi Dinar', '368', 'IQD', 3)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (115, 'IRELAND', 'Euro', '978', 'EUR', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (116, 'ISLE OF MAN', 'Pound Sterling', '826', 'GBP', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (117, 'ISRAEL', 'New Israeli Sheqel', '376', 'ILS', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (118, 'ITALY', 'Euro', '978', 'EUR', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (119, 'JAMAICA', 'Jamaican Dollar', '388', 'JMD', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (120, 'JAPAN', 'Yen', '392', 'JPY', 0)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (121, 'JERSEY', 'Pound Sterling', '826', 'GBP', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (122, 'JORDAN', 'Jordanian Dinar', '400', 'JOD', 3)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (123, 'KAZAKHSTAN', 'Tenge', '398', 'KZT', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (124, 'KENYA', 'Kenyan Shilling', '404', 'KES', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (125, 'KIRIBATI', 'Australian Dollar', '036', 'AUD', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (126, 'KOREA, DEMOCRATIC PEOPLE�S REPUBLIC OF', 'North Korean Won', '408', 'KPW', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (127, 'KOREA, REPUBLIC OF', 'Won', '410', 'KRW', 0)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (128, 'KUWAIT', 'Kuwaiti Dinar', '414', 'KWD', 3)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (129, 'KYRGYZSTAN', 'Som', '417', 'KGS', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (130, 'LAO PEOPLE�S DEMOCRATIC REPUBLIC', 'Kip', '418', 'LAK', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (131, 'LATVIA', 'Euro', '978', 'EUR', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (132, 'LEBANON', 'Lebanese Pound', '422', 'LBP', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (133, 'LESOTHO', 'Loti', '426', 'LSL', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (134, 'LESOTHO', 'Rand', '710', 'ZAR', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (135, 'LIBERIA', 'Liberian Dollar', '430', 'LRD', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (136, 'LIBYA', 'Libyan Dinar', '434', 'LYD', 3)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (137, 'LIECHTENSTEIN', 'Swiss Franc', '756', 'CHF', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (138, 'LITHUANIA', 'Euro', '978', 'EUR', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (139, 'LUXEMBOURG', 'Euro', '978', 'EUR', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (140, 'MACAO', 'Pataca', '446', 'MOP', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (141, 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF', 'Denar', '807', 'MKD', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (142, 'MADAGASCAR', 'Malagasy Ariary', '969', 'MGA', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (143, 'MALAWI', 'Kwacha', '454', 'MWK', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (144, 'MALAYSIA', 'Malaysian Ringgit', '458', 'MYR', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (145, 'MALDIVES', 'Rufiyaa', '462', 'MVR', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (146, 'MALI', 'CFA Franc BCEAO', '952', 'XOF', 0)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (147, 'MALTA', 'Euro', '978', 'EUR', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (148, 'MARSHALL ISLANDS', 'US Dollar', '840', 'USD', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (149, 'MARTINIQUE', 'Euro', '978', 'EUR', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (150, 'MAURITANIA', 'Ouguiya', '478', 'MRO', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (151, 'MAURITIUS', 'Mauritius Rupee', '480', 'MUR', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (152, 'MAYOTTE', 'Euro', '978', 'EUR', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (153, 'MEMBER COUNTRIES OF THE AFRICAN DEVELOPMENT BANK GROUP', 'ADB Unit of Account', '965', 'XUA', 0)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (154, 'MEXICO', 'Mexican Peso', '484', 'MXN', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (155, 'MEXICO', 'Mexican Unidad de Inversion (UDI)', '979', 'MXV', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (156, 'MICRONESIA, FEDERATED STATES OF', 'US Dollar', '840', 'USD', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (157, 'MOLDOVA, REPUBLIC OF', 'Moldovan Leu', '498', 'MDL', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (158, 'MONACO', 'Euro', '978', 'EUR', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (159, 'MONGOLIA', 'Tugrik', '496', 'MNT', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (160, 'MONTENEGRO', 'Euro', '978', 'EUR', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (161, 'MONTSERRAT', 'East Caribbean Dollar', '951', 'XCD', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (162, 'MOROCCO', 'Moroccan Dirham', '504', 'MAD', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (163, 'MOZAMBIQUE', 'Mozambique Metical', '943', 'MZN', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (164, 'MYANMAR', 'Kyat', '104', 'MMK', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (165, 'NAMIBIA', 'Namibia Dollar', '516', 'NAD', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (166, 'NAMIBIA', 'Rand', '710', 'ZAR', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (167, 'NAURU', 'Australian Dollar', '036', 'AUD', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (168, 'NEPAL', 'Nepalese Rupee', '524', 'NPR', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (169, 'NETHERLANDS', 'Euro', '978', 'EUR', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (170, 'NEW CALEDONIA', 'CFP Franc', '953', 'XPF', 0)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (171, 'NEW ZEALAND', 'New Zealand Dollar', '554', 'NZD', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (172, 'NICARAGUA', 'Cordoba Oro', '558', 'NIO', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (173, 'NIGER', 'CFA Franc BCEAO', '952', 'XOF', 0)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (174, 'NIGERIA', 'Naira', '566', 'NGN', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (175, 'NIUE', 'New Zealand Dollar', '554', 'NZD', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (176, 'NORFOLK ISLAND', 'Australian Dollar', '036', 'AUD', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (177, 'NORTHERN MARIANA ISLANDS', 'US Dollar', '840', 'USD', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (178, 'NORWAY', 'Norwegian Krone', '578', 'NOK', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (179, 'OMAN', 'Rial Omani', '512', 'OMR', 3)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (180, 'PAKISTAN', 'Pakistan Rupee', '586', 'PKR', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (181, 'PALAU', 'US Dollar', '840', 'USD', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (182, 'PANAMA', 'Balboa', '590', 'PAB', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (183, 'PANAMA', 'US Dollar', '840', 'USD', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (184, 'PAPUA NEW GUINEA', 'Kina', '598', 'PGK', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (185, 'PARAGUAY', 'Guarani', '600', 'PYG', 0)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (186, 'PERU', 'Nuevo Sol', '604', 'PEN', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (187, 'PHILIPPINES', 'Philippine Peso', '608', 'PHP', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (188, 'PITCAIRN', 'New Zealand Dollar', '554', 'NZD', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (189, 'POLAND', 'Zloty', '985', 'PLN', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (190, 'PORTUGAL', 'Euro', '978', 'EUR', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (191, 'PUERTO RICO', 'US Dollar', '840', 'USD', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (192, 'QATAR', 'Qatari Rial', '634', 'QAR', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (193, 'R�UNION', 'Euro', '978', 'EUR', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (194, 'ROMANIA', 'New Romanian Leu', '946', 'RON', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (195, 'RUSSIAN FEDERATION', 'Russian Ruble', '643', 'RUB', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (196, 'RWANDA', 'Rwanda Franc', '646', 'RWF', 0)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (197, 'SAINT BARTH�LEMY', 'Euro', '978', 'EUR', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (198, 'SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA', 'Saint Helena Pound', '654', 'SHP', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (199, 'SAINT KITTS AND NEVIS', 'East Caribbean Dollar', '951', 'XCD', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (200, 'SAINT LUCIA', 'East Caribbean Dollar', '951', 'XCD', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (201, 'SAINT MARTIN (FRENCH PART)', 'Euro', '978', 'EUR', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (202, 'SAINT PIERRE AND MIQUELON', 'Euro', '978', 'EUR', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (203, 'SAINT VINCENT AND THE GRENADINES', 'East Caribbean Dollar', '951', 'XCD', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (204, 'SAMOA', 'Tala', '882', 'WST', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (205, 'SAN MARINO', 'Euro', '978', 'EUR', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (206, 'SAO TOME AND PRINCIPE', 'Dobra', '678', 'STD', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (207, 'SAUDI ARABIA', 'Saudi Riyal', '682', 'SAR', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (208, 'SENEGAL', 'CFA Franc BCEAO', '952', 'XOF', 0)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (209, 'SERBIA', 'Serbian Dinar', '941', 'RSD', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (210, 'SEYCHELLES', 'Seychelles Rupee', '690', 'SCR', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (211, 'SIERRA LEONE', 'Leone', '694', 'SLL', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (212, 'SINGAPORE', 'Singapore Dollar', '702', 'SGD', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (213, 'SINT MAARTEN (DUTCH PART)', 'Netherlands Antillean Guilder', '532', 'ANG', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (214, 'SISTEMA UNITARIO DE COMPENSACION REGIONAL DE PAGOS SUCRE', 'Sucre', '994', 'XSU', 0)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (215, 'SLOVAKIA', 'Euro', '978', 'EUR', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (216, 'SLOVENIA', 'Euro', '978', 'EUR', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (217, 'SOLOMON ISLANDS', 'Solomon Islands Dollar', '090', 'SBD', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (218, 'SOMALIA', 'Somali Shilling', '706', 'SOS', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (219, 'SOUTH AFRICA', 'Rand', '710', 'ZAR', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (221, 'SOUTH SUDAN', 'South Sudanese Pound', '728', 'SSP', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (222, 'SPAIN', 'Euro', '978', 'EUR', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (223, 'SRI LANKA', 'Sri Lanka Rupee', '144', 'LKR', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (224, 'SUDAN', 'Sudanese Pound', '938', 'SDG', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (225, 'SURINAME', 'Surinam Dollar', '968', 'SRD', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (226, 'SVALBARD AND JAN MAYEN', 'Norwegian Krone', '578', 'NOK', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (227, 'SWAZILAND', 'Lilangeni', '748', 'SZL', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (228, 'SWEDEN', 'Swedish Krona', '752', 'SEK', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (229, 'SWITZERLAND', 'WIR Euro', '947', 'CHE', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (230, 'SWITZERLAND', 'Swiss Franc', '756', 'CHF', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (231, 'SWITZERLAND', 'WIR Franc', '948', 'CHW', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (232, 'SYRIAN ARAB REPUBLIC', 'Syrian Pound', '760', 'SYP', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (233, 'TAIWAN, PROVINCE OF CHINA', 'New Taiwan Dollar', '901', 'TWD', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (234, 'TAJIKISTAN', 'Somoni', '972', 'TJS', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (235, 'TANZANIA, UNITED REPUBLIC OF', 'Tanzanian Shilling', '834', 'TZS', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (236, 'THAILAND', 'Baht', '764', 'THB', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (237, 'TIMOR-LESTE', 'US Dollar', '840', 'USD', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (238, 'TOGO', 'CFA Franc BCEAO', '952', 'XOF', 0)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (239, 'TOKELAU', 'New Zealand Dollar', '554', 'NZD', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (240, 'TONGA', 'Pa�anga', '776', 'TOP', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (241, 'TRINIDAD AND TOBAGO', 'Trinidad and Tobago Dollar', '780', 'TTD', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (242, 'TUNISIA', 'Tunisian Dinar', '788', 'TND', 3)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (243, 'TURKEY', 'Turkish Lira', '949', 'TRY', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (244, 'TURKMENISTAN', 'Turkmenistan New Manat', '934', 'TMT', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (245, 'TURKS AND CAICOS ISLANDS', 'US Dollar', '840', 'USD', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (246, 'TUVALU', 'Australian Dollar', '036', 'AUD', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (247, 'UGANDA', 'Uganda Shilling', '800', 'UGX', 0)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (248, 'UKRAINE', 'Hryvnia', '980', 'UAH', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (249, 'UNITED ARAB EMIRATES', 'UAE Dirham', '784', 'AED', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (250, 'UNITED KINGDOM', 'Pound Sterling', '826', 'GBP', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (251, 'UNITED STATES', 'US Dollar', '840', 'USD', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (252, 'UNITED STATES', 'US Dollar (Next day)', '997', 'USN', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (253, 'UNITED STATES MINOR OUTLYING ISLANDS', 'US Dollar', '840', 'USD', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (254, 'URUGUAY', 'Uruguay Peso en Unidades Indexadas (URUIURUI)', '940', 'UYI', 0)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (255, 'URUGUAY', 'Peso Uruguayo', '858', 'UYU', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (256, 'UZBEKISTAN', 'Uzbekistan Sum', '860', 'UZS', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (257, 'VANUATU', 'Vatu', '548', 'VUV', 0)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (258, 'VENEZUELA, BOLIVARIAN REPUBLIC OF', 'Bolivar', '937', 'VEF', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (259, 'VIET NAM', 'Dong', '704', 'VND', 0)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (260, 'VIRGIN ISLANDS (BRITISH)', 'US Dollar', '840', 'USD', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (261, 'VIRGIN ISLANDS (U.S.)', 'US Dollar', '840', 'USD', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (262, 'WALLIS AND FUTUNA', 'CFP Franc', '953', 'XPF', 0)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (263, 'WESTERN SAHARA', 'Moroccan Dirham', '504', 'MAD', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (264, 'YEMEN', 'Yemeni Rial', '886', 'YER', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (265, 'ZAMBIA', 'Zambian Kwacha', '967', 'ZMW', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (266, 'ZIMBABWE', 'Zimbabwe Dollar', '932', 'ZWL', 2)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (267, 'ZZ01_Bond Markets Unit European_EURCO', 'Bond Markets Unit European Composite Unit (EURCO)', '955', 'XBA', 0)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (268, 'ZZ02_Bond Markets Unit European_EMU-6', 'Bond Markets Unit European Monetary Unit (E.M.U.-6)', '956', 'XBB', 0)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (269, 'ZZ03_Bond Markets Unit European_EUA-9', 'Bond Markets Unit European Unit of Account 9 (E.U.A.-9)', '957', 'XBC', 0)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (270, 'ZZ04_Bond Markets Unit European_EUA-17', 'Bond Markets Unit European Unit of Account 17 (E.U.A.-17)', '958', 'XBD', 0)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (271, 'ZZ06_Testing_Code', 'Codes specifically reserved for testing purposes', '963', 'XTS', 0)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (272, 'ZZ07_No_Currency', 'The codes assigned for transactions where no currency is involved', '999', 'XXX', 0)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (273, 'ZZ08_Gold', 'Gold', '959', 'XAU', 0)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (274, 'ZZ09_Palladium', 'Palladium', '964', 'XPD', 0)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (275, 'ZZ10_Platinum', 'Platinum', '962', 'XPT', 0)
insert into CURRENCY (id, entity, currency, numericCode, alphabeticCode, minorUnit) values (276, 'ZZ11_Silver', 'Silver', '961', 'XAG', 0)
-- Nuevo sol
insert into DENOMINATION (id, currency_id, value) values (1, 186, 0.10)
insert into DENOMINATION (id, currency_id, value) values (2, 186, 0.20)
insert into DENOMINATION (id, currency_id, value) values (3, 186, 0.50)
insert into DENOMINATION (id, currency_id, value) values (4, 186, 1)
insert into DENOMINATION (id, currency_id, value) values (5, 186, 2)
insert into DENOMINATION (id, currency_id, value) values (6, 186, 5)
insert into DENOMINATION (id, currency_id, value) values (7, 186, 10)
insert into DENOMINATION (id, currency_id, value) values (8, 186, 20)
insert into DENOMINATION (id, currency_id, value) values (9, 186, 50)
insert into DENOMINATION (id, currency_id, value) values (10, 186, 100)
insert into DENOMINATION (id, currency_id, value) values (11, 186, 200)
-- Dolar americano
insert into DENOMINATION (id, currency_id, value) values (12, 5, 1)
insert into DENOMINATION (id, currency_id, value) values (13, 5, 2)
insert into DENOMINATION (id, currency_id, value) values (14, 5, 5)
insert into DENOMINATION (id, currency_id, value) values (15, 5, 10)
insert into DENOMINATION (id, currency_id, value) values (16, 5, 20)
insert into DENOMINATION (id, currency_id, value) values (17, 5, 50)
insert into DENOMINATION (id, currency_id, value) values (18, 5, 100)
-- Euro
insert into DENOMINATION (id, currency_id, value) values (19, 2, 1)
insert into DENOMINATION (id, currency_id, value) values (20, 2, 2)
insert into DENOMINATION (id, currency_id, value) values (21, 2, 10)
insert into DENOMINATION (id, currency_id, value) values (22, 2, 20)
insert into DENOMINATION (id, currency_id, value) values (23, 2, 100)
insert into DENOMINATION (id, currency_id, value) values (24, 2, 200)